services:
  mitmproxy:
    #image: mitmproxy/mitmproxy
    build: .

    volumes:
      - .:/home/mitmproxy/scripts
      - ./logs:/home/mitmproxy/logs
      - ./certs:/home/mitmproxy/.mitmproxy
    ports:
      - "8080:8080" # HTTP/TLS Proxy
      - "8081:8081" # Web UI (optional)
    command: >
      sh -c "pip install python-chess && 
      mitmdump -s /home/mitmproxy/scripts/Logger.py
      --set block_global=false
      --set confdir=/home/mitmproxy/.mitmproxy
      --set stream_websockets=true"
